### ISSUE TITLE
context.params being overwriten on fixParams method

### ISSUE THREAD

**Issue by tiagoit** [feathersjs-offline/owndata-ownnet#26]
### Steps to reproduce
- Add any property to context.params.
- Try to access it after wrapping the service.

### Expected behaviour
According to the docs, context.params is writable, so it should not be totally overwritten.

### Actual behaviour
The method `fixParams` at `server/src/index.js` is overwriting the params preserving only query and paginate properties.

**Module versions**: 
"@feathersjs-offline/server": "^1.0.6",

**NodeJS version**: 
v12.20.2

**Comment by mhillerstrom** [comment]
Thank you for this.

**Comment by mhillerstrom** [comment]
Implemented.
