### ISSUE TITLE
Help owndataWrapper or ownnetWrapper not working

### ISSUE THREAD

**Issue by messycoding** [feathersjs-offline/owndata-ownnet#44]
Please look in to my issue again regarding owndataWrapper and ownnetWrapper, both do not work.

https://github.com/feathersjs-offline/owndata-ownnet/issues/43

There is this:

> Error: Unable to resolve module path from /Users/neil/Documents/TESTING/NODE/offlinefirst/offlinefirst/node_modules/node-localstorage/LocalStorage.js: path could not be found within the project or in these directories:
>   node_modules

I already tried installing node-localstorage but still not working.

**Comment by mhillerstrom** [comment]
Please try the new version v1.0.8. Sorry for any inconvenience.
