### ISSUE TITLE
fs package issue under LocalStorage

### ISSUE THREAD

**Issue by messycoding** [feathersjs-offline/owndata-ownnet#46]
This is in relation to the error discussed here.

https://github.com/feathersjs-offline/owndata-ownnet/issues/44

I managed to get rid of the error regarding node-localstorage by installing these packages.

assert, constants, events, path, stream, and fs

however, the package fs has a security issue and it is now suggested to use fs-extra. . now I get a new error.

<img width="572" alt="Screen Shot 2021-07-20 at 1 45 59 PM" src="https://user-images.githubusercontent.com/87465548/126268255-1ec69b0a-d003-47d5-9d23-8758c8e87cf5.png">

I am now clueless as to what to do. Here is my repo

https://github.com/messycoding/myfeathersofflinefirstproject

**Note:** This error will only show if I call

`owndataWrapper(app, '/messages', {});`

**Comment by mhillerstrom** [comment]
Hi,

 

When running `npm run test` I get

 

 

Is this consistent with what you see – or am I missing something?

 

/Michael

 

From: messycoding ***@***.***>
Reply-To: feathersjs-offline/owndata-ownnet ***@***.***>
Date: Tuesday, 20 July 2021 at 07.51
To: feathersjs-offline/owndata-ownnet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [feathersjs-offline/owndata-ownnet] fs package issue underLocalStorage (#46)

 

This is in relation to the error discussed here.

#44

I managed to get rid of the error regarding node-localstorage by installing these packages.

assert, constants, events, path, stream, and fs

however, the package fs has a security issue and it is now suggested to use fs-extra. . now I get a new error.

I am now clueless as to what to do. Here is my repo

https://github.com/messycoding/myfeathersofflinefirstproject

Note: This error will only show if I call

owndataWrapper(app, '/messages', {});

**Comment by messycoding** [comment]
Thank you for the response, the latest React Native version has some Jest compatibility issues that is why you see errors when running the test "npm run test".

So the original error says:

Error: Unable to resolve module **path**

so I did npm install path, now the error says

Error: Unable to resolve module **fs**

so I npm install fs, now the error says  Unable to resolve module  assert, constants, events, and stream

<img width="567" alt="Screen Shot 2021-07-21 at 7 40 11 AM" src="https://user-images.githubusercontent.com/87465548/126408626-17510cf7-5d83-479a-83e8-55f9cbe4b992.png">

I am thinking if this is a machine-related issue?

**Comment by messycoding** [comment]
This probably has something to do with my mac . . thank you so much for the help. . I will now close the case thank you.

**Comment by mhillerstrom** [comment]
Hi,

 

After downgrading Jest to version 26 I got the test to work – without any problems with feathersjs-offline/client v1.0.8. Is this also your experience?

 

Regards,

Michael

 

From: messycoding ***@***.***>
Reply-To: feathersjs-offline/owndata-ownnet ***@***.***>
Date: Wednesday, 21 July 2021 at 02.20
To: feathersjs-offline/owndata-ownnet ***@***.***>
Cc: Michael Hillerström ***@***.***>, Comment ***@***.***>
Subject: Re: [feathersjs-offline/owndata-ownnet] fs package issue underLocalStorage (#46)

 

Closed #46.
